dist: trusty
sudo: required
matrix:
    - TOOLCHAIN=
    - TOOLCHAIN=raspberry.toolchain
before_install:
- sudo apt-get install -y cmake liblog4cpp5-dev liblivemedia-dev libasound2-dev
# for coverage
- pip install --user cpp-coveralls pyYaml
language: cpp
compiler:
- gcc
script:
- if [ "$TOOLCHAIN" != "" ]; then git clone --depth 1 https://github.com/raspberrypi/tools.git rpi_tools && export PATH=$PATH:$(pwd)/rpi_tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin; fi
#build on native system
- cmake . && make && cpack .
#run coverage test
- sudo rm -rf CMakeCache.txt *.a CMakeFiles
- cmake -DCOVERAGE=ON . && make && make test
after_success:
- coveralls --gcov-options '\-lp'
env:
  global:
  - secure: jKV3Hj/lvoNjU2JUSUlLsLAHX+BI0R27+qTEPSihHpNGB+NOvbwlfpisrqxA/9nanVhtq9I3PJi2Jd5Pkg+3TkYvRq62ZT1Ty/DuxbQmMWlhEZT6wxbVS7919OZ3K0WAOizt3/HzSxL5XZheGRAKf89SoUF6mOP4V3DCh5rzze4=
addons:
  coverity_scan:
    project:
      name: mpromonet/v4l2rtspserver
    build_command_prepend: cmake .
    build_command: make
    branch_pattern: master
    notification_email: scan_notifications@example.com
before_deploy:
  - export RELEASE_PKG_FILE=$(ls *.deb)
  - echo "deploying ${RELEASE_PKG_FILE} to GitHub releases"    
deploy:
  provider: releases
  api_key:
    secure: gcQy7QO09vfGtcRMi8D+6VykDfK1tuz1jEZRmJER6eZ0p2gRi4F6mtsMRJWt3QsKkZQWkJpPTvCfv9GyNmWTrZV746y5QVnd+mjPx+6K/LgroK4LWgOgzJ6zQ6qfDKU80GbxJOnNv9/HmIcxSCiactxS50tbvntqpBGCmiIL+4U=
  file: 
    - "${RELEASE_PKG_FILE}"
  skip_cleanup: true
  on:
    repo: mpromonet/v4l2rtspserver
    tags: true
