version: 2
jobs:
  build:
    docker:
      - image: heroku/heroku:16
    steps:
      - checkout
      - run: apt-get update; apt-get install -y --no-install-recommends cmake autoconf automake libtool git make g++ liblog4cpp5-dev liblivemedia-dev
      - run: cmake . && make
      - run: cpack .
      - run: cpack -G TGZ .
      - run: mkdir pkg && cp *.deb pkg && cp *.tar.gz pkg
      - store_artifacts:
          path: pkg       
